import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#23292e',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#23292e',
  },
  loadingText: {
    color: '#fff',
    fontSize: 16,
    marginTop: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#23292e',
    paddingHorizontal: 20,
  },
  errorText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#4FC3F7',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sectionContainer: {
    marginBottom: 32,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
    marginHorizontal: 16,
    marginBottom: 16,
    marginTop: 16,
  },

  // 빠른 선곡 스타일
  quickPickList: {
    paddingLeft: 16,
  },
  quickPickPage: {
    width: screenWidth * 0.85,
    marginRight: 12,
    paddingRight: 4,
  },
  quickPickCard: {
    backgroundColor: '#333',
    borderRadius: 12,
    padding: 20,
    marginRight: 12,
    width: screenWidth * 0.75,
    height: 160,
    justifyContent: 'center',
  },
  songTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
    lineHeight: 22,
  },
  songYomi: {
    color: '#aaa',
    fontSize: 14,
    marginBottom: 4,
    fontStyle: 'italic',
  },
  artistName: {
    color: '#bbb',
    fontSize: 14,
    marginBottom: 12,
  },
  karaokeCodes: {
    flexDirection: 'row',
    gap: 8,
  },
  karaokeCode: {
    backgroundColor: '#4FC3F7',
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  karaokeCodeTJ: {
    backgroundColor: '#4682B4',
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    minWidth: 45,
    textAlign: 'center',
  },
  karaokeCodeKY: {
    backgroundColor: '#EB431E',
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    minWidth: 45,
    textAlign: 'center',
  },

  themeGroupContainer: {
    marginBottom: 32,
  },
  themeGroupTitle: {
    color: '#4FC3F7',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
    marginLeft: 16,
  },
  themeGroupTagline: {
    color: '#4FC3F7',
    fontSize: 16,
    marginBottom: 20,
    marginLeft: 16,
    fontWeight: '700',
  },
  themeSongList: {
    paddingLeft: 16,
  },
  themeHorizontalCard: {
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 12,
    marginRight: 12,
    width: screenWidth * 0.7,
    height: 80,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  themeVerticalCard: {
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 16,
    marginBottom: 8,
    marginHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  themeHorizontalSongCard: {
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 16,
    marginRight: 12,
    width: screenWidth * 0.65,
    minHeight: 130,
  },
  themeHorizontalSongList: {
    paddingLeft: 16,
    paddingRight: 4,
  },
  themeHorizontalSongTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
    lineHeight: 20,
  },
  themeHorizontalSongArtist: {
    color: '#bbb',
    fontSize: 14,
    marginBottom: 12,
  },
  themeHorizontalKaraokeCodes: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 'auto',
  },
  themeHorizontalKaraokeCodeTJ: {
    backgroundColor: '#4682B4',
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    minWidth: 40,
    textAlign: 'center',
  },
  themeHorizontalKaraokeCodeKY: {
    backgroundColor: '#EB431E',
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    minWidth: 40,
    textAlign: 'center',
  },
  themeSongPage: {
    width: screenWidth * 0.85,
    marginRight: 12,
    paddingRight: 4,
  },
  themeSongCard: {
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 16,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 100,
  },
  themeSongInfo: {
    flex: 1,
    marginRight: 12,
  },
  themeSongTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 2,
  },
  themeSongYomi: {
    color: '#aaa',
    fontSize: 13,
    marginBottom: 2,
    fontStyle: 'italic',
  },
  themeSongArtist: {
    color: '#bbb',
    fontSize: 14,
  },
  themeKaraokeCodes: {
    flexDirection: 'row',
    gap: 4,
  },
  themeKaraokeCode: {
    backgroundColor: '#4FC3F7',
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    minWidth: 32,
    textAlign: 'center',
  },
  themeKaraokeCodeTJ: {
    backgroundColor: '#4682B4',
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 4,
    minWidth: 45,
    textAlign: 'center',
  },
  themeKaraokeCodeKY: {
    backgroundColor: '#EB431E',
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 4,
    minWidth: 45,
    textAlign: 'center',
  },
  contentContainer: {
    paddingBottom: 20,
  },
});

export default styles;
